# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactlist/v2/contact_list_common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2
import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.common.v2_pb2 as model

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contactlist.v2.contact_list_common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.kik.gen.contactlist.v2.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/contactlist/v2;contactlist\240\001\001\242\002\016KPBCommonCNLV2'
  _USERFRIENDCONTEXT_SCAN.fields_by_name['scan_code']._options = None
  _USERFRIENDCONTEXT_SCAN.fields_by_name['scan_code']._serialized_options = b'\312\235%\005\010\0010\364\003'
  _USERFRIENDCONTEXT_SCAN.fields_by_name['nonce_key']._options = None
  _USERFRIENDCONTEXT_SCAN.fields_by_name['nonce_key']._serialized_options = b'\312\235%\005\010\0010\364\003'
  _USERFRIENDCONTEXT_WEBKIKME.fields_by_name['related_url']._options = None
  _USERFRIENDCONTEXT_WEBKIKME.fields_by_name['related_url']._serialized_options = b'\312\235%\005\010\0010\210\''
  _USERFRIENDCONTEXT_WEBPROFILEKIKME.fields_by_name['related_url']._options = None
  _USERFRIENDCONTEXT_WEBPROFILEKIKME.fields_by_name['related_url']._serialized_options = b'\312\235%\005\010\0010\210\''
  _USERFRIENDCONTEXT_CARDPROFILEKIKPROTOCOL.fields_by_name['related_card_name']._options = None
  _USERFRIENDCONTEXT_CARDPROFILEKIKPROTOCOL.fields_by_name['related_card_name']._serialized_options = b'\312\235%\005\010\0010\200('
  _USERFRIENDCONTEXT_CARDPROFILEKIKPROTOCOL.fields_by_name['related_url']._options = None
  _USERFRIENDCONTEXT_CARDPROFILEKIKPROTOCOL.fields_by_name['related_url']._serialized_options = b'\312\235%\0030\210\''
  _USERFRIENDCONTEXT_CARDSENDKIKTOUSER.fields_by_name['related_card_name']._options = None
  _USERFRIENDCONTEXT_CARDSENDKIKTOUSER.fields_by_name['related_card_name']._serialized_options = b'\312\235%\005\010\0010\200('
  _USERFRIENDCONTEXT_CARDSENDKIKTOUSER.fields_by_name['related_url']._options = None
  _USERFRIENDCONTEXT_CARDSENDKIKTOUSER.fields_by_name['related_url']._serialized_options = b'\312\235%\0030\210\''
  _USERFRIENDCONTEXT_CARDOPENCONVERSATION.fields_by_name['related_card_name']._options = None
  _USERFRIENDCONTEXT_CARDOPENCONVERSATION.fields_by_name['related_card_name']._serialized_options = b'\312\235%\005\010\0010\200('
  _USERFRIENDCONTEXT_CARDOPENCONVERSATION.fields_by_name['related_url']._options = None
  _USERFRIENDCONTEXT_CARDOPENCONVERSATION.fields_by_name['related_url']._serialized_options = b'\312\235%\0030\210\''
  _USERFRIENDCONTEXT_CARDOPENPROFILE.fields_by_name['related_card_name']._options = None
  _USERFRIENDCONTEXT_CARDOPENPROFILE.fields_by_name['related_card_name']._serialized_options = b'\312\235%\005\010\0010\200('
  _USERFRIENDCONTEXT_CARDOPENPROFILE.fields_by_name['related_url']._options = None
  _USERFRIENDCONTEXT_CARDOPENPROFILE.fields_by_name['related_url']._serialized_options = b'\312\235%\0030\210\''
  _USERFRIENDCONTEXT._serialized_start=138
  _USERFRIENDCONTEXT._serialized_end=3856
  _USERFRIENDCONTEXT_DEFAULTCONTEXT._serialized_start=2716
  _USERFRIENDCONTEXT_DEFAULTCONTEXT._serialized_end=2732
  _USERFRIENDCONTEXT_SCAN._serialized_start=2734
  _USERFRIENDCONTEXT_SCAN._serialized_end=2800
  _USERFRIENDCONTEXT_EXPLICITUSERNAMESEARCH._serialized_start=2802
  _USERFRIENDCONTEXT_EXPLICITUSERNAMESEARCH._serialized_end=2826
  _USERFRIENDCONTEXT_INLINEUSERNAMESEARCH._serialized_start=2828
  _USERFRIENDCONTEXT_INLINEUSERNAMESEARCH._serialized_end=2850
  _USERFRIENDCONTEXT_INLINEPROMOTED._serialized_start=2852
  _USERFRIENDCONTEXT_INLINEPROMOTED._serialized_end=2868
  _USERFRIENDCONTEXT_FUZZYMATCHING._serialized_start=2870
  _USERFRIENDCONTEXT_FUZZYMATCHING._serialized_end=2885
  _USERFRIENDCONTEXT_ADDRESSBOOKMATCHING._serialized_start=2887
  _USERFRIENDCONTEXT_ADDRESSBOOKMATCHING._serialized_end=2908
  _USERFRIENDCONTEXT_PROMOTEDCHATSLIST._serialized_start=2910
  _USERFRIENDCONTEXT_PROMOTEDCHATSLIST._serialized_end=2929
  _USERFRIENDCONTEXT_TALKTOAD._serialized_start=2931
  _USERFRIENDCONTEXT_TALKTOAD._serialized_end=2941
  _USERFRIENDCONTEXT_FINDPEOPLEAD._serialized_start=2943
  _USERFRIENDCONTEXT_FINDPEOPLEAD._serialized_end=2957
  _USERFRIENDCONTEXT_GROUPADDALL._serialized_start=2959
  _USERFRIENDCONTEXT_GROUPADDALL._serialized_end=3017
  _USERFRIENDCONTEXT_GROUPINFOADD._serialized_start=3019
  _USERFRIENDCONTEXT_GROUPINFOADD._serialized_end=3078
  _USERFRIENDCONTEXT_WEBKIKME._serialized_start=3080
  _USERFRIENDCONTEXT_WEBKIKME._serialized_end=3122
  _USERFRIENDCONTEXT_WEBPROFILEKIKME._serialized_start=3124
  _USERFRIENDCONTEXT_WEBPROFILEKIKME._serialized_end=3173
  _USERFRIENDCONTEXT_CARDPROFILEKIKPROTOCOL._serialized_start=3175
  _USERFRIENDCONTEXT_CARDPROFILEKIKPROTOCOL._serialized_end=3267
  _USERFRIENDCONTEXT_CARDSENDKIKTOUSER._serialized_start=3269
  _USERFRIENDCONTEXT_CARDSENDKIKTOUSER._serialized_end=3356
  _USERFRIENDCONTEXT_CARDOPENCONVERSATION._serialized_start=3358
  _USERFRIENDCONTEXT_CARDOPENCONVERSATION._serialized_end=3448
  _USERFRIENDCONTEXT_CARDOPENPROFILE._serialized_start=3450
  _USERFRIENDCONTEXT_CARDOPENPROFILE._serialized_end=3535
  _USERFRIENDCONTEXT_SUGGESTFRIEND._serialized_start=3537
  _USERFRIENDCONTEXT_SUGGESTFRIEND._serialized_end=3552
  _USERFRIENDCONTEXT_FRIENDPICKER._serialized_start=3554
  _USERFRIENDCONTEXT_FRIENDPICKER._serialized_end=3568
  _USERFRIENDCONTEXT_LINKATTRIBUTION._serialized_start=3570
  _USERFRIENDCONTEXT_LINKATTRIBUTION._serialized_end=3587
  _USERFRIENDCONTEXT_USERNAMEMENTION._serialized_start=3589
  _USERFRIENDCONTEXT_USERNAMEMENTION._serialized_end=3606
  _USERFRIENDCONTEXT_BOTMENTION._serialized_start=3608
  _USERFRIENDCONTEXT_BOTMENTION._serialized_end=3620
  _USERFRIENDCONTEXT_BOTMENTIONREPLY._serialized_start=3622
  _USERFRIENDCONTEXT_BOTMENTIONREPLY._serialized_end=3639
  _USERFRIENDCONTEXT_BOTSHOP._serialized_start=3641
  _USERFRIENDCONTEXT_BOTSHOP._serialized_end=3650
  _USERFRIENDCONTEXT_GROUPMEMBERADD._serialized_start=3652
  _USERFRIENDCONTEXT_GROUPMEMBERADD._serialized_end=3668
  _USERFRIENDCONTEXT_GROUPINFOMENUADD._serialized_start=3670
  _USERFRIENDCONTEXT_GROUPINFOMENUADD._serialized_end=3733
  _USERFRIENDCONTEXT_GROUPMENUADD._serialized_start=3735
  _USERFRIENDCONTEXT_GROUPMENUADD._serialized_end=3794
  _USERFRIENDCONTEXT_PULLUSERNAMESEARCH._serialized_start=3796
  _USERFRIENDCONTEXT_PULLUSERNAMESEARCH._serialized_end=3816
  _USERFRIENDCONTEXT_SENDTOUSERNAMESEARCH._serialized_start=3818
  _USERFRIENDCONTEXT_SENDTOUSERNAMESEARCH._serialized_end=3840
# @@protoc_insertion_point(module_scope)
