# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kin/payment/v1/payment_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kin/payment/v1/payment_common.proto',
  package='common.kin.payment.v1',
  syntax='proto3',
  serialized_pb=_b('\n#kin/payment/v1/payment_common.proto\x12\x15\x63ommon.kin.payment.v1\x1a\x19protobuf_validation.proto\x1a\x12\x63ommon_model.proto\"\xb6\x01\n\x0bPaymentInfo\x12/\n\x07\x66\x65\x61ture\x18\x01 \x01(\x0e\x32\x1e.common.kin.payment.v1.Feature\x12\x38\n\x0c\x66\x65\x61ture_data\x18\x02 \x01(\x0b\x32\".common.kin.payment.v1.FeatureData\x12<\n\nkin_amount\x18\x03 \x01(\x0b\x32 .common.kin.payment.v1.KinAmountB\x06\xca\x9d%\x02\x08\x01\"l\n\x0b\x46\x65\x61tureData\x12U\n\x1bpublic_group_admin_tip_data\x18\x01 \x01(\x0b\x32..common.kin.payment.v1.PublicGroupAdminTipDataH\x00\x42\x06\n\x04kind\"D\n\x17PublicGroupAdminTipData\x12)\n\x05group\x18\x01 \x01(\x0b\x32\x12.common.XiGroupJidB\x06\xca\x9d%\x02\x08\x01\"\x1b\n\tKinAmount\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01*2\n\x07\x46\x65\x61ture\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x1a\n\x16PUBLIC_GROUP_ADMIN_TIP\x10\x01\x42o\n\x19\x63om.kik.kin.payment.modelZRgithub.com/kikinteractive/xiphias-model-common/generated/go/kin/payment/v1;paymentb\x06proto3')
  ,
  dependencies=[protobuf__validation__pb2.DESCRIPTOR,common__model__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FEATURE = _descriptor.EnumDescriptor(
  name='Feature',
  full_name='common.kin.payment.v1.Feature',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLIC_GROUP_ADMIN_TIP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=503,
  serialized_end=553,
)
_sym_db.RegisterEnumDescriptor(_FEATURE)

Feature = enum_type_wrapper.EnumTypeWrapper(_FEATURE)
UNKNOWN = 0
PUBLIC_GROUP_ADMIN_TIP = 1



_PAYMENTINFO = _descriptor.Descriptor(
  name='PaymentInfo',
  full_name='common.kin.payment.v1.PaymentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='common.kin.payment.v1.PaymentInfo.feature', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_data', full_name='common.kin.payment.v1.PaymentInfo.feature_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kin_amount', full_name='common.kin.payment.v1.PaymentInfo.kin_amount', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\002\010\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=292,
)


_FEATUREDATA = _descriptor.Descriptor(
  name='FeatureData',
  full_name='common.kin.payment.v1.FeatureData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_group_admin_tip_data', full_name='common.kin.payment.v1.FeatureData.public_group_admin_tip_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='common.kin.payment.v1.FeatureData.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=294,
  serialized_end=402,
)


_PUBLICGROUPADMINTIPDATA = _descriptor.Descriptor(
  name='PublicGroupAdminTipData',
  full_name='common.kin.payment.v1.PublicGroupAdminTipData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='common.kin.payment.v1.PublicGroupAdminTipData.group', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\002\010\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=472,
)


_KINAMOUNT = _descriptor.Descriptor(
  name='KinAmount',
  full_name='common.kin.payment.v1.KinAmount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='common.kin.payment.v1.KinAmount.amount', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=501,
)

_PAYMENTINFO.fields_by_name['feature'].enum_type = _FEATURE
_PAYMENTINFO.fields_by_name['feature_data'].message_type = _FEATUREDATA
_PAYMENTINFO.fields_by_name['kin_amount'].message_type = _KINAMOUNT
_FEATUREDATA.fields_by_name['public_group_admin_tip_data'].message_type = _PUBLICGROUPADMINTIPDATA
_FEATUREDATA.oneofs_by_name['kind'].fields.append(
  _FEATUREDATA.fields_by_name['public_group_admin_tip_data'])
_FEATUREDATA.fields_by_name['public_group_admin_tip_data'].containing_oneof = _FEATUREDATA.oneofs_by_name['kind']
_PUBLICGROUPADMINTIPDATA.fields_by_name['group'].message_type = common__model__pb2._XIGROUPJID
DESCRIPTOR.message_types_by_name['PaymentInfo'] = _PAYMENTINFO
DESCRIPTOR.message_types_by_name['FeatureData'] = _FEATUREDATA
DESCRIPTOR.message_types_by_name['PublicGroupAdminTipData'] = _PUBLICGROUPADMINTIPDATA
DESCRIPTOR.message_types_by_name['KinAmount'] = _KINAMOUNT
DESCRIPTOR.enum_types_by_name['Feature'] = _FEATURE

PaymentInfo = _reflection.GeneratedProtocolMessageType('PaymentInfo', (_message.Message,), dict(
  DESCRIPTOR = _PAYMENTINFO,
  __module__ = 'kin.payment.v1.payment_common_pb2'
  # @@protoc_insertion_point(class_scope:common.kin.payment.v1.PaymentInfo)
  ))
_sym_db.RegisterMessage(PaymentInfo)

FeatureData = _reflection.GeneratedProtocolMessageType('FeatureData', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREDATA,
  __module__ = 'kin.payment.v1.payment_common_pb2'
  # @@protoc_insertion_point(class_scope:common.kin.payment.v1.FeatureData)
  ))
_sym_db.RegisterMessage(FeatureData)

PublicGroupAdminTipData = _reflection.GeneratedProtocolMessageType('PublicGroupAdminTipData', (_message.Message,), dict(
  DESCRIPTOR = _PUBLICGROUPADMINTIPDATA,
  __module__ = 'kin.payment.v1.payment_common_pb2'
  # @@protoc_insertion_point(class_scope:common.kin.payment.v1.PublicGroupAdminTipData)
  ))
_sym_db.RegisterMessage(PublicGroupAdminTipData)

KinAmount = _reflection.GeneratedProtocolMessageType('KinAmount', (_message.Message,), dict(
  DESCRIPTOR = _KINAMOUNT,
  __module__ = 'kin.payment.v1.payment_common_pb2'
  # @@protoc_insertion_point(class_scope:common.kin.payment.v1.KinAmount)
  ))
_sym_db.RegisterMessage(KinAmount)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031com.kik.kin.payment.modelZRgithub.com/kikinteractive/xiphias-model-common/generated/go/kin/payment/v1;payment'))
_PAYMENTINFO.fields_by_name['kin_amount'].has_options = True
_PAYMENTINFO.fields_by_name['kin_amount']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\002\010\001'))
_PUBLICGROUPADMINTIPDATA.fields_by_name['group'].has_options = True
_PUBLICGROUPADMINTIPDATA.fields_by_name['group']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\002\010\001'))
# @@protoc_insertion_point(module_scope)
