# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagepath/v1/link_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.messagepath.v1_pb2 as core_message_common

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messagepath.v1.link_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\242\002\004MPTH'
  _LINKMESSAGEATTACHMENT.fields_by_name['uris']._options = None
  _LINKMESSAGEATTACHMENT.fields_by_name['uris']._serialized_options = b'\312\235%\007\010\001x\001\200\001\n'
  _LINKMESSAGEATTACHMENT.fields_by_name['title']._options = None
  _LINKMESSAGEATTACHMENT.fields_by_name['title']._serialized_options = b'\312\235%\0030\350\007'
  _LINKMESSAGEATTACHMENT.fields_by_name['text']._options = None
  _LINKMESSAGEATTACHMENT.fields_by_name['text']._serialized_options = b'\312\235%\0030\320\017'
  _LINKMESSAGEATTACHMENT._serialized_start=130
  _LINKMESSAGEATTACHMENT._serialized_end=477
# @@protoc_insertion_point(module_scope)
