# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagepath/v1/text_markdown.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messagepath/v1/text_markdown.proto',
  package='common.messagepath.v1',
  syntax='proto3',
  serialized_pb=_b('\n\"messagepath/v1/text_markdown.proto\x12\x15\x63ommon.messagepath.v1\x1a\x19protobuf_validation.proto\"3\n\x16TextMarkdownAttachment\x12\x19\n\x08markdown\x18\x01 \x01(\tB\x07\xca\x9d%\x03\x30\xc4\x13\x42z\n\x19\x63om.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\xa2\x02\x04MPTHb\x06proto3')
  ,
  dependencies=[protobuf__validation__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TEXTMARKDOWNATTACHMENT = _descriptor.Descriptor(
  name='TextMarkdownAttachment',
  full_name='common.messagepath.v1.TextMarkdownAttachment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='markdown', full_name='common.messagepath.v1.TextMarkdownAttachment.markdown', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\0030\304\023'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['TextMarkdownAttachment'] = _TEXTMARKDOWNATTACHMENT

TextMarkdownAttachment = _reflection.GeneratedProtocolMessageType('TextMarkdownAttachment', (_message.Message,), dict(
  DESCRIPTOR = _TEXTMARKDOWNATTACHMENT,
  __module__ = 'messagepath.v1.text_markdown_pb2'
  # @@protoc_insertion_point(class_scope:common.messagepath.v1.TextMarkdownAttachment)
  ))
_sym_db.RegisterMessage(TextMarkdownAttachment)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031com.kik.messagepath.modelZVgithub.com/kikinteractive/xiphias-model-common/generated/go/messagepath/v1;messagepath\242\002\004MPTH'))
_TEXTMARKDOWNATTACHMENT.fields_by_name['markdown'].has_options = True
_TEXTMARKDOWNATTACHMENT.fields_by_name['markdown']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\0030\304\023'))
# @@protoc_insertion_point(module_scope)
