# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antispam/iospushverification/v1/iospushverification_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAantispam/iospushverification/v1/iospushverification_service.proto\x12&mobile.antispam.iospushverification.v1\x1a\x19protobuf_validation.proto\"6\n\x1aSubmitVoipPushTokenRequest\x12\x18\n\x05token\x18\x01 \x01(\tB\t\xca\x9d%\x05(\x01\x30\xff\x01\"\x8b\x01\n\x1bSubmitVoipPushTokenResponse\x12Z\n\x06result\x18\x01 \x01(\x0e\x32J.mobile.antispam.iospushverification.v1.SubmitVoipPushTokenResponse.Result\"\x10\n\x06Result\x12\x06\n\x02OK\x10\x00\":\n\x19\x46orwardPushPayloadRequest\x12\x1d\n\x07payload\x18\x01 \x01(\tB\x0c\xca\x9d%\x08\x08\x01(\x01\x30\xa8\xc3\x01\"\x89\x01\n\x1a\x46orwardPushPayloadResponse\x12Y\n\x06result\x18\x01 \x01(\x0e\x32I.mobile.antispam.iospushverification.v1.ForwardPushPayloadResponse.Result\"\x10\n\x06Result\x12\x06\n\x02OK\x10\x00\x32\xd8\x02\n\x13IosPushVerification\x12\xa0\x01\n\x13SubmitVoipPushToken\x12\x42.mobile.antispam.iospushverification.v1.SubmitVoipPushTokenRequest\x1a\x43.mobile.antispam.iospushverification.v1.SubmitVoipPushTokenResponse\"\x00\x12\x9d\x01\n\x12\x46orwardPushPayload\x12\x41.mobile.antispam.iospushverification.v1.ForwardPushPayloadRequest\x1a\x42.mobile.antispam.iospushverification.v1.ForwardPushPayloadResponse\"\x00\x42\x99\x01\n(com.kik.antispam.iospushverification.rpcZmgithub.com/kikinteractive/xiphias-api-mobile/generated/go/antispam/iospushverification/v1;iospushverificationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antispam.iospushverification.v1.iospushverification_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n(com.kik.antispam.iospushverification.rpcZmgithub.com/kikinteractive/xiphias-api-mobile/generated/go/antispam/iospushverification/v1;iospushverification'
  _SUBMITVOIPPUSHTOKENREQUEST.fields_by_name['token']._options = None
  _SUBMITVOIPPUSHTOKENREQUEST.fields_by_name['token']._serialized_options = b'\312\235%\005(\0010\377\001'
  _FORWARDPUSHPAYLOADREQUEST.fields_by_name['payload']._options = None
  _FORWARDPUSHPAYLOADREQUEST.fields_by_name['payload']._serialized_options = b'\312\235%\010\010\001(\0010\250\303\001'
  _SUBMITVOIPPUSHTOKENREQUEST._serialized_start=136
  _SUBMITVOIPPUSHTOKENREQUEST._serialized_end=190
  _SUBMITVOIPPUSHTOKENRESPONSE._serialized_start=193
  _SUBMITVOIPPUSHTOKENRESPONSE._serialized_end=332
  _SUBMITVOIPPUSHTOKENRESPONSE_RESULT._serialized_start=316
  _SUBMITVOIPPUSHTOKENRESPONSE_RESULT._serialized_end=332
  _FORWARDPUSHPAYLOADREQUEST._serialized_start=334
  _FORWARDPUSHPAYLOADREQUEST._serialized_end=392
  _FORWARDPUSHPAYLOADRESPONSE._serialized_start=395
  _FORWARDPUSHPAYLOADRESPONSE._serialized_end=532
  _FORWARDPUSHPAYLOADRESPONSE_RESULT._serialized_start=316
  _FORWARDPUSHPAYLOADRESPONSE_RESULT._serialized_end=332
  _IOSPUSHVERIFICATION._serialized_start=535
  _IOSPUSHVERIFICATION._serialized_end=879
# @@protoc_insertion_point(module_scope)
