# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2
import kik_unofficial.protobuf.kik_options_pb2 as kik__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ommon_rpc.proto\x12\x06\x63ommon\x1a google/protobuf/descriptor.proto\x1a\x19protobuf_validation.proto\x1a\x12\x63ommon_model.proto\x1a\x11kik_options.proto\"\r\n\x0bVoidRequest\"\x0e\n\x0cVoidResponse\"1\n\x0bXiRequestId\x12\"\n\x02id\x18\x01 \x01(\x0b\x32\x0e.common.XiUuidB\x06\xca\x9d%\x02\x08\x01\"*\n\x0eXiRoutingToken\x12\x18\n\x05token\x18\x01 \x01(\tB\t\xca\x9d%\x05(\x01\x30\x80\x01\"\x85\x01\n\x15SelfDescribingMessage\x12@\n\x14\x66ield_descriptor_set\x18\x01 \x01(\x0b\x32\".google.protobuf.FileDescriptorSet\x12\x14\n\x0cmessage_name\x18\x02 \x01(\t\x12\x14\n\x0cmessage_data\x18\x03 \x01(\x0c\x42q\n\x13\x63om.kik.xiphias.rpcB\x0e\x43ommonRpcProtoP\x01ZBgithub.com/kikinteractive/xiphias-model-common/generated/go;common\xaa\xa3*\x02\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023com.kik.xiphias.rpcB\016CommonRpcProtoP\001ZBgithub.com/kikinteractive/xiphias-model-common/generated/go;common\252\243*\002\020\001'
  _XIREQUESTID.fields_by_name['id']._options = None
  _XIREQUESTID.fields_by_name['id']._serialized_options = b'\312\235%\002\010\001'
  _XIROUTINGTOKEN.fields_by_name['token']._options = None
  _XIROUTINGTOKEN.fields_by_name['token']._serialized_options = b'\312\235%\005(\0010\200\001'
  _VOIDREQUEST._serialized_start=128
  _VOIDREQUEST._serialized_end=141
  _VOIDRESPONSE._serialized_start=143
  _VOIDRESPONSE._serialized_end=157
  _XIREQUESTID._serialized_start=159
  _XIREQUESTID._serialized_end=208
  _XIROUTINGTOKEN._serialized_start=210
  _XIROUTINGTOKEN._serialized_end=252
  _SELFDESCRIBINGMESSAGE._serialized_start=255
  _SELFDESCRIBINGMESSAGE._serialized_end=388
# @@protoc_insertion_point(module_scope)
