# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile/v2/profile_common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprofile/v2/profile_common.proto\x12\x11\x63ommon.profile.v2\x1a\x19protobuf_validation.proto\"R\n\x15\x44isplayNameComponents\x12\x1d\n\nfirst_name\x18\x01 \x01(\tB\t\xca\x9d%\x05\x08\x01\x30\xff\x01\x12\x1a\n\tlast_name\x18\x02 \x01(\tB\x07\xca\x9d%\x03\x30\xff\x01\x42}\n\x16\x63om.kik.gen.profile.v2ZNgithub.com/kikinteractive/xiphias-model-common/generated/go/profile/v2;profile\xa2\x02\x12KPBCommonProfileV2b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile.v2.profile_common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.kik.gen.profile.v2ZNgithub.com/kikinteractive/xiphias-model-common/generated/go/profile/v2;profile\242\002\022KPBCommonProfileV2'
  _DISPLAYNAMECOMPONENTS.fields_by_name['first_name']._options = None
  _DISPLAYNAMECOMPONENTS.fields_by_name['first_name']._serialized_options = b'\312\235%\005\010\0010\377\001'
  _DISPLAYNAMECOMPONENTS.fields_by_name['last_name']._options = None
  _DISPLAYNAMECOMPONENTS.fields_by_name['last_name']._serialized_options = b'\312\235%\0030\377\001'
  _DISPLAYNAMECOMPONENTS._serialized_start=81
  _DISPLAYNAMECOMPONENTS._serialized_end=163
# @@protoc_insertion_point(module_scope)
