# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity/v1/subscription_common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.entity.v1_pb2 as entity_common


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#entity/v1/subscription_common.proto\x12\x10\x63ommon.entity.v1\x1a\x19protobuf_validation.proto\x1a\x1d\x65ntity/v1/entity_common.proto\x1a\x15\x63ommon/v1/model.proto\"/\n\x0fRosterSyncToken\x12\x1c\n\x07payload\x18\x01 \x01(\x0c\x42\x0b\xca\x9d%\x07\x08\x01(\x01\x30\x80(\"C\n\x0f\x41liasBlockEntry\x12\x30\n\talias_jid\x18\x01 \x01(\x0b\x32\x15.common.v1.XiAliasJidB\x06\xca\x9d%\x02\x08\x01\"\xf3\x01\n\x0bRosterEntry\x12<\n\tuser_data\x18\x01 \x01(\x0b\x32\'.common.entity.v1.EntityUserRosterEntryH\x00\x12>\n\ngroup_data\x18\x02 \x01(\x0b\x32(.common.entity.v1.EntityGroupRosterEntryH\x00\x12=\n\x10\x61lias_block_data\x18\x04 \x01(\x0b\x32!.common.entity.v1.AliasBlockEntryH\x00\x12\x12\n\nis_blocked\x18\x03 \x01(\x08\x42\x13\n\x11roster_entry_kindBn\n\x14\x63om.kik.entity.modelZLgithub.com/kikinteractive/xiphias-model-common/generated/go/entity/v1;entity\xa0\x01\x01\xa2\x02\x04SUBSb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entity.v1.subscription_common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.kik.entity.modelZLgithub.com/kikinteractive/xiphias-model-common/generated/go/entity/v1;entity\240\001\001\242\002\004SUBS'
  _ROSTERSYNCTOKEN.fields_by_name['payload']._options = None
  _ROSTERSYNCTOKEN.fields_by_name['payload']._serialized_options = b'\312\235%\007\010\001(\0010\200('
  _ALIASBLOCKENTRY.fields_by_name['alias_jid']._options = None
  _ALIASBLOCKENTRY.fields_by_name['alias_jid']._serialized_options = b'\312\235%\002\010\001'
  _ROSTERSYNCTOKEN._serialized_start=138
  _ROSTERSYNCTOKEN._serialized_end=185
  _ALIASBLOCKENTRY._serialized_start=187
  _ALIASBLOCKENTRY._serialized_end=254
  _ROSTERENTRY._serialized_start=257
  _ROSTERENTRY._serialized_end=500
# @@protoc_insertion_point(module_scope)
