# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kin/authentication/v1/authentication_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2
from kik_unofficial.protobuf.common.v1 import model_pb2 as common_dot_v1_dot_model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kin/authentication/v1/authentication_service.proto',
  package='mobile.kin.authentication.v1',
  syntax='proto3',
  serialized_pb=_b('\n2kin/authentication/v1/authentication_service.proto\x12\x1cmobile.kin.authentication.v1\x1a\x19protobuf_validation.proto\x1a\x12\x63ommon_model.proto\x1a\x15\x63ommon/v1/model.proto\"I\n\x16GenerateUserJwtRequest\x12/\n\x08user_jid\x18\x01 \x01(\x0b\x32\x15.common.XiBareUserJidB\x06\xca\x9d%\x02\x08\x01\"\xfb\x01\n\x17GenerateUserJwtResponse\x12L\n\x06result\x18\x01 \x01(\x0e\x32<.mobile.kin.authentication.v1.GenerateUserJwtResponse.Result\x12N\n\x10rejection_reason\x18\x02 \x01(\x0b\x32\x34.mobile.kin.authentication.v1.UserJwtRejectionReason\x12\"\n\x08user_jwt\x18\x03 \x01(\x0b\x32\x10.common.v1.XiJWT\"\x1e\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\"\x98\x01\n\x16UserJwtRejectionReason\x12G\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x39.mobile.kin.authentication.v1.UserJwtRejectionReason.Code\"5\n\x04\x43ode\x12\x0b\n\x07UNKNOWN\x10\x00\x12 \n\x1cREJECTED_USER_NOT_AUTHORIZED\x10\x01\x32\x90\x01\n\x0e\x41uthentication\x12~\n\x0fGenerateUserJwt\x12\x34.mobile.kin.authentication.v1.GenerateUserJwtRequest\x1a\x35.mobile.kin.authentication.v1.GenerateUserJwtResponseB\x80\x01\n\x1e\x63om.kik.kin.authentication.rpcZ^github.com/kikinteractive/xiphias-api-mobile/generated/go/kin/authentication/v1;authenticationb\x06proto3')
  ,
  dependencies=[protobuf__validation__pb2.DESCRIPTOR,common__model__pb2.DESCRIPTOR,common_dot_v1_dot_model__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_GENERATEUSERJWTRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='mobile.kin.authentication.v1.GenerateUserJwtResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=451,
  serialized_end=481,
)
_sym_db.RegisterEnumDescriptor(_GENERATEUSERJWTRESPONSE_RESULT)

_USERJWTREJECTIONREASON_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='mobile.kin.authentication.v1.UserJwtRejectionReason.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REJECTED_USER_NOT_AUTHORIZED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=583,
  serialized_end=636,
)
_sym_db.RegisterEnumDescriptor(_USERJWTREJECTIONREASON_CODE)


_GENERATEUSERJWTREQUEST = _descriptor.Descriptor(
  name='GenerateUserJwtRequest',
  full_name='mobile.kin.authentication.v1.GenerateUserJwtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_jid', full_name='mobile.kin.authentication.v1.GenerateUserJwtRequest.user_jid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\002\010\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=227,
)


_GENERATEUSERJWTRESPONSE = _descriptor.Descriptor(
  name='GenerateUserJwtResponse',
  full_name='mobile.kin.authentication.v1.GenerateUserJwtResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='mobile.kin.authentication.v1.GenerateUserJwtResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rejection_reason', full_name='mobile.kin.authentication.v1.GenerateUserJwtResponse.rejection_reason', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_jwt', full_name='mobile.kin.authentication.v1.GenerateUserJwtResponse.user_jwt', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GENERATEUSERJWTRESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=481,
)


_USERJWTREJECTIONREASON = _descriptor.Descriptor(
  name='UserJwtRejectionReason',
  full_name='mobile.kin.authentication.v1.UserJwtRejectionReason',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mobile.kin.authentication.v1.UserJwtRejectionReason.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERJWTREJECTIONREASON_CODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=636,
)

_GENERATEUSERJWTREQUEST.fields_by_name['user_jid'].message_type = common__model__pb2._XIBAREUSERJID
_GENERATEUSERJWTRESPONSE.fields_by_name['result'].enum_type = _GENERATEUSERJWTRESPONSE_RESULT
_GENERATEUSERJWTRESPONSE.fields_by_name['rejection_reason'].message_type = _USERJWTREJECTIONREASON
_GENERATEUSERJWTRESPONSE.fields_by_name['user_jwt'].message_type = common_dot_v1_dot_model__pb2._XIJWT
_GENERATEUSERJWTRESPONSE_RESULT.containing_type = _GENERATEUSERJWTRESPONSE
_USERJWTREJECTIONREASON.fields_by_name['code'].enum_type = _USERJWTREJECTIONREASON_CODE
_USERJWTREJECTIONREASON_CODE.containing_type = _USERJWTREJECTIONREASON
DESCRIPTOR.message_types_by_name['GenerateUserJwtRequest'] = _GENERATEUSERJWTREQUEST
DESCRIPTOR.message_types_by_name['GenerateUserJwtResponse'] = _GENERATEUSERJWTRESPONSE
DESCRIPTOR.message_types_by_name['UserJwtRejectionReason'] = _USERJWTREJECTIONREASON

GenerateUserJwtRequest = _reflection.GeneratedProtocolMessageType('GenerateUserJwtRequest', (_message.Message,), dict(
  DESCRIPTOR = _GENERATEUSERJWTREQUEST,
  __module__ = 'kin.authentication.v1.authentication_service_pb2'
  # @@protoc_insertion_point(class_scope:mobile.kin.authentication.v1.GenerateUserJwtRequest)
  ))
_sym_db.RegisterMessage(GenerateUserJwtRequest)

GenerateUserJwtResponse = _reflection.GeneratedProtocolMessageType('GenerateUserJwtResponse', (_message.Message,), dict(
  DESCRIPTOR = _GENERATEUSERJWTRESPONSE,
  __module__ = 'kin.authentication.v1.authentication_service_pb2'
  # @@protoc_insertion_point(class_scope:mobile.kin.authentication.v1.GenerateUserJwtResponse)
  ))
_sym_db.RegisterMessage(GenerateUserJwtResponse)

UserJwtRejectionReason = _reflection.GeneratedProtocolMessageType('UserJwtRejectionReason', (_message.Message,), dict(
  DESCRIPTOR = _USERJWTREJECTIONREASON,
  __module__ = 'kin.authentication.v1.authentication_service_pb2'
  # @@protoc_insertion_point(class_scope:mobile.kin.authentication.v1.UserJwtRejectionReason)
  ))
_sym_db.RegisterMessage(UserJwtRejectionReason)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.kik.kin.authentication.rpcZ^github.com/kikinteractive/xiphias-api-mobile/generated/go/kin/authentication/v1;authentication'))
_GENERATEUSERJWTREQUEST.fields_by_name['user_jid'].has_options = True
_GENERATEUSERJWTREQUEST.fields_by_name['user_jid']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\002\010\001'))
# @@protoc_insertion_point(module_scope)
