# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: abtesting/v1/ab_testing_shared.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='abtesting/v1/ab_testing_shared.proto',
  package='common.abtesting.v1',
  syntax='proto3',
  serialized_pb=_b('\n$abtesting/v1/ab_testing_shared.proto\x12\x13\x63ommon.abtesting.v1\x1a\x19protobuf_validation.proto\"i\n\nExperiment\x12\x19\n\x04name\x18\x01 \x01(\tB\x0b\xca\x9d%\x07\x08\x01(\x01\x30\xff\x01\x12\x1c\n\x07variant\x18\x02 \x01(\tB\x0b\xca\x9d%\x07\x08\x01(\x01\x30\xff\x01\x12\"\n\rexperiment_id\x18\x03 \x01(\tB\x0b\xca\x9d%\x07\x08\x00(\x00\x30\xff\x01\x42r\n\x15\x63om.kik.abtesting.rpcZRgithub.com/kikinteractive/xiphias-model-common/generated/go/abtesting/v1;abtesting\xa2\x02\x04XIABb\x06proto3')
  ,
  dependencies=[protobuf__validation__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXPERIMENT = _descriptor.Descriptor(
  name='Experiment',
  full_name='common.abtesting.v1.Experiment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='common.abtesting.v1.Experiment.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\007\010\001(\0010\377\001'))),
    _descriptor.FieldDescriptor(
      name='variant', full_name='common.abtesting.v1.Experiment.variant', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\007\010\001(\0010\377\001'))),
    _descriptor.FieldDescriptor(
      name='experiment_id', full_name='common.abtesting.v1.Experiment.experiment_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\007\010\000(\0000\377\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['Experiment'] = _EXPERIMENT

Experiment = _reflection.GeneratedProtocolMessageType('Experiment', (_message.Message,), dict(
  DESCRIPTOR = _EXPERIMENT,
  __module__ = 'abtesting.v1.ab_testing_shared_pb2'
  # @@protoc_insertion_point(class_scope:common.abtesting.v1.Experiment)
  ))
_sym_db.RegisterMessage(Experiment)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025com.kik.abtesting.rpcZRgithub.com/kikinteractive/xiphias-model-common/generated/go/abtesting/v1;abtesting\242\002\004XIAB'))
_EXPERIMENT.fields_by_name['name'].has_options = True
_EXPERIMENT.fields_by_name['name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\007\010\001(\0010\377\001'))
_EXPERIMENT.fields_by_name['variant'].has_options = True
_EXPERIMENT.fields_by_name['variant']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\007\010\001(\0010\377\001'))
_EXPERIMENT.fields_by_name['experiment_id'].has_options = True
_EXPERIMENT.fields_by_name['experiment_id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\007\010\000(\0000\377\001'))
# @@protoc_insertion_point(module_scope)
