# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: badgecount/v1/badge_count_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.common_model_pb2 as common__model__pb2
import kik_unofficial.protobuf.common_rpc_pb2 as common__rpc__pb2
import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'badgecount/v1/badge_count_service.proto\x12\x14mobile.badgecount.v1\x1a\x12\x63ommon_model.proto\x1a\x10\x63ommon_rpc.proto\x1a\x19protobuf_validation.proto\"}\n\x1dSetUnreadConversationsRequest\x12\x46\n\x14\x63onversations_unread\x18\x01 \x03(\x0b\x32\x1c.common.XiBareUserOrGroupJidB\n\xca\x9d%\x06\x08\x00\x80\x01\xc8\x01\x12\x14\n\x0cunread_count\x18\x02 \x01(\r2q\n\nBadgeCount\x12\x63\n\x16SetUnreadConversations\x12\x33.mobile.badgecount.v1.SetUnreadConversationsRequest\x1a\x14.common.VoidResponseBl\n\x16\x63om.kik.badgecount.rpcZRgithub.com/kikinteractive/xiphias-api-mobile/generated/go/badgecount/v1;badgecountb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'badgecount.v1.badge_count_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.kik.badgecount.rpcZRgithub.com/kikinteractive/xiphias-api-mobile/generated/go/badgecount/v1;badgecount'
  _SETUNREADCONVERSATIONSREQUEST.fields_by_name['conversations_unread']._options = None
  _SETUNREADCONVERSATIONSREQUEST.fields_by_name['conversations_unread']._serialized_options = b'\312\235%\006\010\000\200\001\310\001'
  _SETUNREADCONVERSATIONSREQUEST._serialized_start=130
  _SETUNREADCONVERSATIONSREQUEST._serialized_end=255
  _BADGECOUNT._serialized_start=257
  _BADGECOUNT._serialized_end=370
# @@protoc_insertion_point(module_scope)
