# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chats/v2/chats_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kik_unofficial.protobuf.common.v2 import model_pb2 as common_dot_v2_dot_model__pb2
import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
from kik_unofficial.protobuf.google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chats/v2/chats_common.proto',
  package='common.chats.v2',
  syntax='proto3',
  serialized_pb=_b('\n\x1b\x63hats/v2/chats_common.proto\x12\x0f\x63ommon.chats.v2\x1a\x15\x63ommon/v2/model.proto\x1a\x19protobuf_validation.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x0b\x43hatThemeId\x12#\n\x02id\x18\x01 \x01(\x0b\x32\x0f.common.v2.UuidB\x06\xca\x9d%\x02\x08\x01\"\x90\x01\n\nMuteStatus\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".common.chats.v2.MuteStatus.Status\x12*\n\x06\x65xpiry\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\"\n\x06Status\x12\r\n\tNOT_MUTED\x10\x00\x12\t\n\x05MUTED\x10\x01\x42u\n\x14\x63om.kik.gen.chats.v2ZJgithub.com/kikinteractive/xiphias-model-common/generated/go/chats/v2;chats\xa2\x02\x10KPBCommonChatsV2b\x06proto3')
  ,
  dependencies=[common_dot_v2_dot_model__pb2.DESCRIPTOR,protobuf__validation__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MUTESTATUS_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='common.chats.v2.MuteStatus.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_MUTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=294,
  serialized_end=328,
)
_sym_db.RegisterEnumDescriptor(_MUTESTATUS_STATUS)


_CHATTHEMEID = _descriptor.Descriptor(
  name='ChatThemeId',
  full_name='common.chats.v2.ChatThemeId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.chats.v2.ChatThemeId.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\002\010\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=181,
)


_MUTESTATUS = _descriptor.Descriptor(
  name='MuteStatus',
  full_name='common.chats.v2.MuteStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='common.chats.v2.MuteStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='common.chats.v2.MuteStatus.expiry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MUTESTATUS_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=328,
)

_CHATTHEMEID.fields_by_name['id'].message_type = common_dot_v2_dot_model__pb2._UUID
_MUTESTATUS.fields_by_name['status'].enum_type = _MUTESTATUS_STATUS
_MUTESTATUS.fields_by_name['expiry'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_MUTESTATUS_STATUS.containing_type = _MUTESTATUS
DESCRIPTOR.message_types_by_name['ChatThemeId'] = _CHATTHEMEID
DESCRIPTOR.message_types_by_name['MuteStatus'] = _MUTESTATUS

ChatThemeId = _reflection.GeneratedProtocolMessageType('ChatThemeId', (_message.Message,), dict(
  DESCRIPTOR = _CHATTHEMEID,
  __module__ = 'chats.v2.chats_common_pb2'
  # @@protoc_insertion_point(class_scope:common.chats.v2.ChatThemeId)
  ))
_sym_db.RegisterMessage(ChatThemeId)

MuteStatus = _reflection.GeneratedProtocolMessageType('MuteStatus', (_message.Message,), dict(
  DESCRIPTOR = _MUTESTATUS,
  __module__ = 'chats.v2.chats_common_pb2'
  # @@protoc_insertion_point(class_scope:common.chats.v2.MuteStatus)
  ))
_sym_db.RegisterMessage(MuteStatus)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024com.kik.gen.chats.v2ZJgithub.com/kikinteractive/xiphias-model-common/generated/go/chats/v2;chats\242\002\020KPBCommonChatsV2'))
_CHATTHEMEID.fields_by_name['id'].has_options = True
_CHATTHEMEID.fields_by_name['id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\002\010\001'))
# @@protoc_insertion_point(module_scope)
