# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal/v2/model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2
import kik_unofficial.protobuf.common.v2_pb2 as model

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal.v2.model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.kik.gen.signal.v2ZLgithub.com/kikinteractive/xiphias-model-common/generated/go/signal/v2;signal\242\002\021KPBCommonSignalV2'
  _SIGNAL_ID.fields_by_name['raw_value']._options = None
  _SIGNAL_ID.fields_by_name['raw_value']._serialized_options = b'\312\235%\006\010\001(\0200 '
  _SIGNAL.fields_by_name['id']._options = None
  _SIGNAL.fields_by_name['id']._serialized_options = b'\312\235%\002\010\001'
  _PERSONASIGNAL.fields_by_name['persona_id']._options = None
  _PERSONASIGNAL.fields_by_name['persona_id']._serialized_options = b'\312\235%\002\010\000'
  _SIGNAL._serialized_start=94
  _SIGNAL._serialized_end=312
  _SIGNAL_ID._serialized_start=269
  _SIGNAL_ID._serialized_end=304
  _GLOBALSIGNAL._serialized_start=314
  _GLOBALSIGNAL._serialized_end=328
  _PERSONASIGNAL._serialized_start=330
  _PERSONASIGNAL._serialized_end=395
# @@protoc_insertion_point(module_scope)
