# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: push/v2/push_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kik_unofficial.protobuf.protobuf_validation_pb2 as protobuf__validation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='push/v2/push_common.proto',
  package='common.push.v2',
  syntax='proto3',
  serialized_pb=_b('\n\x19push/v2/push_common.proto\x12\x0e\x63ommon.push.v2\x1a\x19protobuf_validation.proto\"\x9d\x03\n\tPushToken\x12H\n\x12\x61ndroid_push_token\x18\x01 \x01(\x0b\x32*.common.push.v2.PushToken.AndroidPushTokenH\x00\x12@\n\x0eios_push_token\x18\x02 \x01(\x0b\x32&.common.push.v2.PushToken.IosPushTokenH\x00\x1a,\n\x10\x41ndroidPushToken\x12\x18\n\x05token\x18\x01 \x01(\tB\t\xca\x9d%\x05\x08\x01\x30\x80\x08\x1a\xcd\x01\n\x0cIosPushToken\x12\x18\n\x05token\x18\x01 \x01(\tB\t\xca\x9d%\x05\x08\x01\x30\x80\x08\x12\x39\n\x04type\x18\x02 \x01(\x0e\x32+.common.push.v2.PushToken.IosPushToken.Type\"h\n\x04Type\x12\x17\n\x13\x41PPSTORE_PRODUCTION\x10\x00\x12\x14\n\x10\x41PPSTORE_SANDBOX\x10\x01\x12\x19\n\x15\x45NTERPRISE_PRODUCTION\x10\x02\x12\x16\n\x12\x45NTERPRISE_SANDBOX\x10\x03\x42\x06\n\x04kindBq\n\x13\x63om.kik.gen.push.v2ZHgithub.com/kikinteractive/xiphias-model-common/generated/go/push/v2;push\xa2\x02\x0fKPBCommonPushV2b\x06proto3')
  ,
  dependencies=[protobuf__validation__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PUSHTOKEN_IOSPUSHTOKEN_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='common.push.v2.PushToken.IosPushToken.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='APPSTORE_PRODUCTION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPSTORE_SANDBOX', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTERPRISE_PRODUCTION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTERPRISE_SANDBOX', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=374,
  serialized_end=478,
)
_sym_db.RegisterEnumDescriptor(_PUSHTOKEN_IOSPUSHTOKEN_TYPE)


_PUSHTOKEN_ANDROIDPUSHTOKEN = _descriptor.Descriptor(
  name='AndroidPushToken',
  full_name='common.push.v2.PushToken.AndroidPushToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='common.push.v2.PushToken.AndroidPushToken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\005\010\0010\200\010'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=270,
)

_PUSHTOKEN_IOSPUSHTOKEN = _descriptor.Descriptor(
  name='IosPushToken',
  full_name='common.push.v2.PushToken.IosPushToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='common.push.v2.PushToken.IosPushToken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\005\010\0010\200\010'))),
    _descriptor.FieldDescriptor(
      name='type', full_name='common.push.v2.PushToken.IosPushToken.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PUSHTOKEN_IOSPUSHTOKEN_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=478,
)

_PUSHTOKEN = _descriptor.Descriptor(
  name='PushToken',
  full_name='common.push.v2.PushToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='android_push_token', full_name='common.push.v2.PushToken.android_push_token', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ios_push_token', full_name='common.push.v2.PushToken.ios_push_token', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PUSHTOKEN_ANDROIDPUSHTOKEN, _PUSHTOKEN_IOSPUSHTOKEN, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='common.push.v2.PushToken.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=73,
  serialized_end=486,
)

_PUSHTOKEN_ANDROIDPUSHTOKEN.containing_type = _PUSHTOKEN
_PUSHTOKEN_IOSPUSHTOKEN.fields_by_name['type'].enum_type = _PUSHTOKEN_IOSPUSHTOKEN_TYPE
_PUSHTOKEN_IOSPUSHTOKEN.containing_type = _PUSHTOKEN
_PUSHTOKEN_IOSPUSHTOKEN_TYPE.containing_type = _PUSHTOKEN_IOSPUSHTOKEN
_PUSHTOKEN.fields_by_name['android_push_token'].message_type = _PUSHTOKEN_ANDROIDPUSHTOKEN
_PUSHTOKEN.fields_by_name['ios_push_token'].message_type = _PUSHTOKEN_IOSPUSHTOKEN
_PUSHTOKEN.oneofs_by_name['kind'].fields.append(
  _PUSHTOKEN.fields_by_name['android_push_token'])
_PUSHTOKEN.fields_by_name['android_push_token'].containing_oneof = _PUSHTOKEN.oneofs_by_name['kind']
_PUSHTOKEN.oneofs_by_name['kind'].fields.append(
  _PUSHTOKEN.fields_by_name['ios_push_token'])
_PUSHTOKEN.fields_by_name['ios_push_token'].containing_oneof = _PUSHTOKEN.oneofs_by_name['kind']
DESCRIPTOR.message_types_by_name['PushToken'] = _PUSHTOKEN

PushToken = _reflection.GeneratedProtocolMessageType('PushToken', (_message.Message,), dict(

  AndroidPushToken = _reflection.GeneratedProtocolMessageType('AndroidPushToken', (_message.Message,), dict(
    DESCRIPTOR = _PUSHTOKEN_ANDROIDPUSHTOKEN,
    __module__ = 'push.v2.push_common_pb2'
    # @@protoc_insertion_point(class_scope:common.push.v2.PushToken.AndroidPushToken)
    ))
  ,

  IosPushToken = _reflection.GeneratedProtocolMessageType('IosPushToken', (_message.Message,), dict(
    DESCRIPTOR = _PUSHTOKEN_IOSPUSHTOKEN,
    __module__ = 'push.v2.push_common_pb2'
    # @@protoc_insertion_point(class_scope:common.push.v2.PushToken.IosPushToken)
    ))
  ,
  DESCRIPTOR = _PUSHTOKEN,
  __module__ = 'push.v2.push_common_pb2'
  # @@protoc_insertion_point(class_scope:common.push.v2.PushToken)
  ))
_sym_db.RegisterMessage(PushToken)
_sym_db.RegisterMessage(PushToken.AndroidPushToken)
_sym_db.RegisterMessage(PushToken.IosPushToken)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023com.kik.gen.push.v2ZHgithub.com/kikinteractive/xiphias-model-common/generated/go/push/v2;push\242\002\017KPBCommonPushV2'))
_PUSHTOKEN_ANDROIDPUSHTOKEN.fields_by_name['token'].has_options = True
_PUSHTOKEN_ANDROIDPUSHTOKEN.fields_by_name['token']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\005\010\0010\200\010'))
_PUSHTOKEN_IOSPUSHTOKEN.fields_by_name['token'].has_options = True
_PUSHTOKEN_IOSPUSHTOKEN.fields_by_name['token']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\312\235%\005\010\0010\200\010'))
# @@protoc_insertion_point(module_scope)
